<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>

// 20230705182025
// https://apis.data.go.kr/B552584/ArpltnInforInqireSvc/getCtprvnRltmMesureDnsty?serviceKey=sv0E5AnjNnQVhZHxGExJHyFyM2pjTpl3vBy4FshUC4HnxVrJRZKWghRZAA%2BKBTRViiwyMZV6QFU5aiomzA3%2BbQ%3D%3D&returnType=json&numOfRows=100&pageNo=1&sidoName=%EC%84%9C%EC%9A%B8&ver=1.0

{
  "response": {
    "body": {
      "totalCount": 40,
      "items": [
        {
          "so2Grade": "1",
          "coFlag": null,
          "khaiValue": "-",
          "so2Value": "0.002",
          "coValue": "0.5",
          "pm25Flag": null,
          "pm10Flag": "통신장애",
          "o3Grade": "2",
          "pm10Value": "-",
          "khaiGrade": null,
          "pm25Value": "28",
          "sidoName": "서울",
          "no2Flag": null,
          "no2Grade": "1",
          "o3Flag": null,
          "pm25Grade": "2",
          "so2Flag": null,
          "dataTime": "2023-07-05 18:00",
          "coGrade": "1",
          "no2Value": "0.015",
          "stationName": "중구",
          "pm10Grade": null,
          "o3Value": "0.056"
        },
        {
          "so2Grade": null,
          "coFlag": "통신장애",
          "khaiValue": "-",
          "so2Value": "-",
          "coValue": "-",
          "pm25Flag": "통신장애",
          "pm10Flag": "통신장애",
          "o3Grade": null,
          "pm10Value": "-",
          "khaiGrade": null,
          "pm25Value": "-",
          "sidoName": "서울",
          "no2Flag": "통신장애",
          "no2Grade": null,
          "o3Flag": "통신장애",
          "pm25Grade": null,
          "so2Flag": "통신장애",
          "dataTime": "2023-07-05 18:00",
          "coGrade": null,
          "no2Value": "-",
          "stationName": "한강대로",
          "pm10Grade": null,
          "o3Value": "-"
        },
        {
          "so2Grade": "1",
          "coFlag": null,
          "khaiValue": "83",
          "so2Value": "0.003",
          "coValue": "0.5",
          "pm25Flag": null,
          "pm10Flag": null,
          "o3Grade": "2",
          "pm10Value": "27",
          "khaiGrade": "2",
          "pm25Value": "19",
          "sidoName": "서울",
          "no2Flag": null,
          "no2Grade": "1",
          "o3Flag": null,
          "pm25Grade": "1",
          "so2Flag": null,
          "dataTime": "2023-07-05 18:00",
          "coGrade": "1",
          "no2Value": "0.013",
          "stationName": "종로구",
          "pm10Grade": "1",
          "o3Value": "0.069"
        },
        {
          "so2Grade": "1",
          "coFlag": null,
          "khaiValue": "70",
          "so2Value": "0.004",
          "coValue": "0.5",
          "pm25Flag": null,
          "pm10Flag": null,
          "o3Grade": "2",
          "pm10Value": "41",
          "khaiGrade": "2",
          "pm25Value": "22",
          "sidoName": "서울",
          "no2Flag": null,
          "no2Grade": "1",
          "o3Flag": null,
          "pm25Grade": "2",
          "so2Flag": null,
          "dataTime": "2023-07-05 18:00",
          "coGrade": "1",
          "no2Value": "0.016",
          "stationName": "청계천로",
          "pm10Grade": "2",
          "o3Value": "0.054"
        },
        {
          "so2Grade": "1",
          "coFlag": null,
          "khaiValue": "63",
          "so2Value": "0.003",
          "coValue": "0.7",
          "pm25Flag": null,
          "pm10Flag": null,
          "o3Grade": "2",
          "pm10Value": "31",
          "khaiGrade": "2",
          "pm25Value": "20",
          "sidoName": "서울",
          "no2Flag": null,
          "no2Grade": "1",
          "o3Flag": null,
          "pm25Grade": "1",
          "so2Flag": null,
          "dataTime": "2023-07-05 18:00",
          "coGrade": "1",
          "no2Value": "0.025",
          "stationName": "종로",
          "pm10Grade": "2",
          "o3Value": "0.045"
        },
        {
          "so2Grade": "1",
          "coFlag": null,
          "khaiValue": "87",
          "so2Value": "0.003",
          "coValue": "0.5",
          "pm25Flag": null,
          "pm10Flag": null,
          "o3Grade": "2",
          "pm10Value": "30",
          "khaiGrade": "2",
          "pm25Value": "23",
          "sidoName": "서울",
          "no2Flag": null,
          "no2Grade": "1",
          "o3Flag": null,
          "pm25Grade": "2",
          "so2Flag": null,
          "dataTime": "2023-07-05 18:00",
          "coGrade": "1",
          "no2Value": "0.018",
          "stationName": "용산구",
          "pm10Grade": "2",
          "o3Value": "0.075"
        },
        {
          "so2Grade": "1",
          "coFlag": null,
          "khaiValue": "83",
          "so2Value": "0.003",
          "coValue": "0.3",
          "pm25Flag": null,
          "pm10Flag": null,
          "o3Grade": "2",
          "pm10Value": "29",
          "khaiGrade": "2",
          "pm25Value": "19",
          "sidoName": "서울",
          "no2Flag": null,
          "no2Grade": "1",
          "o3Flag": null,
          "pm25Grade": "1",
          "so2Flag": null,
          "dataTime": "2023-07-05 18:00",
          "coGrade": "1",
          "no2Value": "0.013",
          "stationName": "광진구",
          "pm10Grade": "1",
          "o3Value": "0.070"
        },
        {
          "so2Grade": "1",
          "coFlag": null,
          "khaiValue": "82",
          "so2Value": "0.003",
          "coValue": "0.5",
          "pm25Flag": null,
          "pm10Flag": null,
          "o3Grade": "2",
          "pm10Value": "32",
          "khaiGrade": "2",
          "pm25Value": "24",
          "sidoName": "서울",
          "no2Flag": null,
          "no2Grade": "1",
          "o3Flag": null,
          "pm25Grade": "2",
          "so2Flag": null,
          "dataTime": "2023-07-05 18:00",
          "coGrade": "1",
          "no2Value": "0.015",
          "stationName": "성동구",
          "pm10Grade": "2",
          "o3Value": "0.069"
        },
        {
          "so2Grade": "1",
          "coFlag": null,
          "khaiValue": "72",
          "so2Value": "0.002",
          "coValue": "0.7",
          "pm25Flag": null,
          "pm10Flag": null,
          "o3Grade": "2",
          "pm10Value": "37",
          "khaiGrade": "2",
          "pm25Value": "17",
          "sidoName": "서울",
          "no2Flag": null,
          "no2Grade": "2",
          "o3Flag": null,
          "pm25Grade": "1",
          "so2Flag": null,
          "dataTime": "2023-07-05 18:00",
          "coGrade": "1",
          "no2Value": "0.031",
          "stationName": "강변북로",
          "pm10Grade": "2",
          "o3Value": "0.056"
        },
        {
          "so2Grade": "1",
          "coFlag": null,
          "khaiValue": "-",
          "so2Value": "0.002",
          "coValue": "0.4",
          "pm25Flag": null,
          "pm10Flag": "통신장애",
          "o3Grade": "2",
          "pm10Value": "-",
          "khaiGrade": null,
          "pm25Value": "22",
          "sidoName": "서울",
          "no2Flag": null,
          "no2Grade": "1",
          "o3Flag": null,
          "pm25Grade": "2",
          "so2Flag": null,
          "dataTime": "2023-07-05 18:00",
          "coGrade": "1",
          "no2Value": "0.014",
          "stationName": "중랑구",
          "pm10Grade": null,
          "o3Value": "0.066"
        },
        {
          "so2Grade": "1",
          "coFlag": null,
          "khaiValue": "83",
          "so2Value": "0.003",
          "coValue": "0.5",
          "pm25Flag": null,
          "pm10Flag": null,
          "o3Grade": "2",
          "pm10Value": "51",
          "khaiGrade": "2",
          "pm25Value": "21",
          "sidoName": "서울",
          "no2Flag": null,
          "no2Grade": "1",
          "o3Flag": null,
          "pm25Grade": "2",
          "so2Flag": null,
          "dataTime": "2023-07-05 18:00",
          "coGrade": "1",
          "no2Value": "0.012",
          "stationName": "동대문구",
          "pm10Grade": "2",
          "o3Value": "0.070"
        },
        {
          "so2Grade": "1",
          "coFlag": null,
          "khaiValue": "-",
          "so2Value": "0.003",
          "coValue": "0.5",
          "pm25Flag": null,
          "pm10Flag": null,
          "o3Grade": "2",
          "pm10Value": "35",
          "khaiGrade": null,
          "pm25Value": "22",
          "sidoName": "서울",
          "no2Flag": null,
          "no2Grade": null,
          "o3Flag": null,
          "pm25Grade": "2",
          "so2Flag": null,
          "dataTime": "2023-07-05 18:00",
          "coGrade": "1",
          "no2Value": "0.030",
          "stationName": "홍릉로",
          "pm10Grade": "2",
          "o3Value": "0.057"
        },
        {
          "so2Grade": "1",
          "coFlag": null,
          "khaiValue": "79",
          "so2Value": "0.003",
          "coValue": "0.4",
          "pm25Flag": null,
          "pm10Flag": null,
          "o3Grade": "2",
          "pm10Value": "29",
          "khaiGrade": "2",
          "pm25Value": "26",
          "sidoName": "서울",
          "no2Flag": null,
          "no2Grade": "1",
          "o3Flag": null,
          "pm25Grade": "2",
          "so2Flag": null,
          "dataTime": "2023-07-05 18:00",
          "coGrade": "1",
          "no2Value": "0.014",
          "stationName": "성북구",
          "pm10Grade": "1",
          "o3Value": "0.064"
        },
        {
          "so2Grade": "1",
          "coFlag": null,
          "khaiValue": "-",
          "so2Value": "0.002",
          "coValue": "0.6",
          "pm25Flag": null,
          "pm10Flag": null,
          "o3Grade": "2",
          "pm10Value": "50",
          "khaiGrade": null,
          "pm25Value": "23",
          "sidoName": "서울",
          "no2Flag": null,
          "no2Grade": null,
          "o3Flag": null,
          "pm25Grade": "2",
          "so2Flag": null,
          "dataTime": "2023-07-05 18:00",
          "coGrade": "1",
          "no2Value": "0.031",
          "stationName": "정릉로",
          "pm10Grade": "2",
          "o3Value": "0.049"
        },
        {
          "so2Grade": "1",
          "coFlag": null,
          "khaiValue": "88",
          "so2Value": "0.002",
          "coValue": "0.4",
          "pm25Flag": null,
          "pm10Flag": null,
          "o3Grade": "2",
          "pm10Value": "31",
          "khaiGrade": "2",
          "pm25Value": "31",
          "sidoName": "서울",
          "no2Flag": null,
          "no2Grade": "1",
          "o3Flag": null,
          "pm25Grade": "2",
          "so2Flag": null,
          "dataTime": "2023-07-05 18:00",
          "coGrade": "1",
          "no2Value": "0.008",
          "stationName": "도봉구",
          "pm10Grade": "1",
          "o3Value": "0.075"
        },
        {
          "so2Grade": "1",
          "coFlag": null,
          "khaiValue": "75",
          "so2Value": "0.003",
          "coValue": "0.6",
          "pm25Flag": null,
          "pm10Flag": null,
          "o3Grade": "2",
          "pm10Value": "36",
          "khaiGrade": "2",
          "pm25Value": "26",
          "sidoName": "서울",
          "no2Flag": null,
          "no2Grade": "1",
          "o3Flag": null,
          "pm25Grade": "2",
          "so2Flag": null,
          "dataTime": "2023-07-05 18:00",
          "coGrade": "1",
          "no2Value": "0.012",
          "stationName": "은평구",
          "pm10Grade": "2",
          "o3Value": "0.060"
        },
        {
          "so2Grade": "1",
          "coFlag": null,
          "khaiValue": "87",
          "so2Value": "0.003",
          "coValue": "0.4",
          "pm25Flag": null,
          "pm10Flag": null,
          "o3Grade": "2",
          "pm10Value": "32",
          "khaiGrade": "2",
          "pm25Value": "21",
          "sidoName": "서울",
          "no2Flag": null,
          "no2Grade": "1",
          "o3Flag": null,
          "pm25Grade": "1",
          "so2Flag": null,
          "dataTime": "2023-07-05 18:00",
          "coGrade": "1",
          "no2Value": "0.015",
          "stationName": "서대문구",
          "pm10Grade": "1",
          "o3Value": "0.075"
        },
        {
          "so2Grade": "1",
          "coFlag": null,
          "khaiValue": "90",
          "so2Value": "0.003",
          "coValue": "0.5",
          "pm25Flag": null,
          "pm10Flag": null,
          "o3Grade": "2",
          "pm10Value": "40",
          "khaiGrade": "2",
          "pm25Value": "22",
          "sidoName": "서울",
          "no2Flag": null,
          "no2Grade": "1",
          "o3Flag": null,
          "pm25Grade": "2",
          "so2Flag": null,
          "dataTime": "2023-07-05 18:00",
          "coGrade": "1",
          "no2Value": "0.011",
          "stationName": "마포구",
          "pm10Grade": "2",
          "o3Value": "0.079"
        },
        {
          "so2Grade": "1",
          "coFlag": null,
          "khaiValue": "61",
          "so2Value": "0.003",
          "coValue": "0.6",
          "pm25Flag": null,
          "pm10Flag": null,
          "o3Grade": "2",
          "pm10Value": "38",
          "khaiGrade": "2",
          "pm25Value": "22",
          "sidoName": "서울",
          "no2Flag": null,
          "no2Grade": "1",
          "o3Flag": null,
          "pm25Grade": "2",
          "so2Flag": null,
          "dataTime": "2023-07-05 18:00",
          "coGrade": "1",
          "no2Value": "0.029",
          "stationName": "신촌로",
          "pm10Grade": "2",
          "o3Value": "0.043"
        },
        {
          "so2Grade": "1",
          "coFlag": null,
          "khaiValue": "88",
          "so2Value": "0.003",
          "coValue": "0.5",
          "pm25Flag": null,
          "pm10Flag": null,
          "o3Grade": "2",
          "pm10Value": "35",
          "khaiGrade": "2",
          "pm25Value": "25",
          "sidoName": "서울",
          "no2Flag": null,
          "no2Grade": "1",
          "o3Flag": null,
          "pm25Grade": "2",
          "so2Flag": null,
          "dataTime": "2023-07-05 18:00",
          "coGrade": "1",
          "no2Value": "0.012",
          "stationName": "강서구",
          "pm10Grade": "2",
          "o3Value": "0.075"
        },
        {
          "so2Grade": "1",
          "coFlag": null,
          "khaiValue": "79",
          "so2Value": "0.003",
          "coValue": "0.4",
          "pm25Flag": null,
          "pm10Flag": null,
          "o3Grade": "2",
          "pm10Value": "34",
          "khaiGrade": "2",
          "pm25Value": "19",
          "sidoName": "서울",
          "no2Flag": null,
          "no2Grade": "1",
          "o3Flag": null,
          "pm25Grade": "2",
          "so2Flag": null,
          "dataTime": "2023-07-05 18:00",
          "coGrade": "1",
          "no2Value": "0.020",
          "stationName": "공항대로",
          "pm10Grade": "1",
          "o3Value": "0.064"
        },
        {
          "so2Grade": "1",
          "coFlag": null,
          "khaiValue": "78",
          "so2Value": "0.002",
          "coValue": "0.4",
          "pm25Flag": null,
          "pm10Flag": null,
          "o3Grade": "2",
          "pm10Value": "28",
          "khaiGrade": "2",
          "pm25Value": "20",
          "sidoName": "서울",
          "no2Flag": null,
          "no2Grade": "1",
          "o3Flag": null,
          "pm25Grade": "1",
          "so2Flag": null,
          "dataTime": "2023-07-05 18:00",
          "coGrade": "1",
          "no2Value": "0.007",
          "stationName": "구로구",
          "pm10Grade": "1",
          "o3Value": "0.064"
        },
        {
          "so2Grade": "1",
          "coFlag": null,
          "khaiValue": "87",
          "so2Value": "0.002",
          "coValue": "0.5",
          "pm25Flag": null,
          "pm10Flag": null,
          "o3Grade": "2",
          "pm10Value": "37",
          "khaiGrade": "2",
          "pm25Value": "19",
          "sidoName": "서울",
          "no2Flag": null,
          "no2Grade": "1",
          "o3Flag": null,
          "pm25Grade": "1",
          "so2Flag": null,
          "dataTime": "2023-07-05 18:00",
          "coGrade": "1",
          "no2Value": "0.011",
          "stationName": "영등포구",
          "pm10Grade": "2",
          "o3Value": "0.074"
        },
        {
          "so2Grade": "1",
          "coFlag": null,
          "khaiValue": "68",
          "so2Value": "0.002",
          "coValue": "0.6",
          "pm25Flag": null,
          "pm10Flag": null,
          "o3Grade": "2",
          "pm10Value": "32",
          "khaiGrade": "2",
          "pm25Value": "21",
          "sidoName": "서울",
          "no2Flag": null,
          "no2Grade": "1",
          "o3Flag": null,
          "pm25Grade": "2",
          "so2Flag": null,
          "dataTime": "2023-07-05 18:00",
          "coGrade": "1",
          "no2Value": "0.030",
          "stationName": "영등포로",
          "pm10Grade": "2",
          "o3Value": "0.051"
        },
        {
          "so2Grade": "1",
          "coFlag": null,
          "khaiValue": "88",
          "so2Value": "0.002",
          "coValue": "0.4",
          "pm25Flag": null,
          "pm10Flag": null,
          "o3Grade": "2",
          "pm10Value": "33",
          "khaiGrade": "2",
          "pm25Value": "24",
          "sidoName": "서울",
          "no2Flag": null,
          "no2Grade": "1",
          "o3Flag": null,
          "pm25Grade": "2",
          "so2Flag": null,
          "dataTime": "2023-07-05 18:00",
          "coGrade": "1",
          "no2Value": "0.008",
          "stationName": "동작구",
          "pm10Grade": "1",
          "o3Value": "0.075"
        },
        {
          "so2Grade": "1",
          "coFlag": null,
          "khaiValue": "83",
          "so2Value": "0.003",
          "coValue": "0.6",
          "pm25Flag": null,
          "pm10Flag": null,
          "o3Grade": "2",
          "pm10Value": "37",
          "khaiGrade": "2",
          "pm25Value": "25",
          "sidoName": "서울",
          "no2Flag": null,
          "no2Grade": "1",
          "o3Flag": null,
          "pm25Grade": "2",
          "so2Flag": null,
          "dataTime": "2023-07-05 18:00",
          "coGrade": "1",
          "no2Value": "0.027",
          "stationName": "동작대로 중앙차로",
          "pm10Grade": "2",
          "o3Value": "0.070"
        },
        {
          "so2Grade": "1",
          "coFlag": null,
          "khaiValue": "87",
          "so2Value": "0.003",
          "coValue": "0.6",
          "pm25Flag": null,
          "pm10Flag": null,
          "o3Grade": "2",
          "pm10Value": "46",
          "khaiGrade": "2",
          "pm25Value": "24",
          "sidoName": "서울",
          "no2Flag": null,
          "no2Grade": "1",
          "o3Flag": null,
          "pm25Grade": "2",
          "so2Flag": null,
          "dataTime": "2023-07-05 18:00",
          "coGrade": "1",
          "no2Value": "0.011",
          "stationName": "관악구",
          "pm10Grade": "2",
          "o3Value": "0.075"
        },
        {
          "so2Grade": "1",
          "coFlag": null,
          "khaiValue": "86",
          "so2Value": "0.003",
          "coValue": "0.5",
          "pm25Flag": null,
          "pm10Flag": null,
          "o3Grade": "2",
          "pm10Value": "35",
          "khaiGrade": "2",
          "pm25Value": "25",
          "sidoName": "서울",
          "no2Flag": null,
          "no2Grade": "1",
          "o3Flag": null,
          "pm25Grade": "2",
          "so2Flag": null,
          "dataTime": "2023-07-05 18:00",
          "coGrade": "1",
          "no2Value": "0.011",
          "stationName": "강남구",
          "pm10Grade": "2",
          "o3Value": "0.073"
        },
        {
          "so2Grade": "1",
          "coFlag": null,
          "khaiValue": "81",
          "so2Value": "0.003",
          "coValue": "0.5",
          "pm25Flag": null,
          "pm10Flag": null,
          "o3Grade": "2",
          "pm10Value": "39",
          "khaiGrade": "2",
          "pm25Value": "17",
          "sidoName": "서울",
          "no2Flag": null,
          "no2Grade": "1",
          "o3Flag": null,
          "pm25Grade": "1",
          "so2Flag": null,
          "dataTime": "2023-07-05 18:00",
          "coGrade": "1",
          "no2Value": "0.013",
          "stationName": "서초구",
          "pm10Grade": "2",
          "o3Value": "0.067"
        },
        {
          "so2Grade": "1",
          "coFlag": null,
          "khaiValue": "70",
          "so2Value": "0.002",
          "coValue": "0.7",
          "pm25Flag": null,
          "pm10Flag": null,
          "o3Grade": "2",
          "pm10Value": "38",
          "khaiGrade": "2",
          "pm25Value": "24",
          "sidoName": "서울",
          "no2Flag": null,
          "no2Grade": "1",
          "o3Flag": null,
          "pm25Grade": "2",
          "so2Flag": null,
          "dataTime": "2023-07-05 18:00",
          "coGrade": "1",
          "no2Value": "0.017",
          "stationName": "도산대로",
          "pm10Grade": "2",
          "o3Value": "0.054"
        },
        {
          "so2Grade": "1",
          "coFlag": null,
          "khaiValue": "65",
          "so2Value": "0.002",
          "coValue": "0.5",
          "pm25Flag": null,
          "pm10Flag": null,
          "o3Grade": "2",
          "pm10Value": "31",
          "khaiGrade": "2",
          "pm25Value": "21",
          "sidoName": "서울",
          "no2Flag": null,
          "no2Grade": "1",
          "o3Flag": null,
          "pm25Grade": "1",
          "so2Flag": null,
          "dataTime": "2023-07-05 18:00",
          "coGrade": "1",
          "no2Value": "0.030",
          "stationName": "강남대로",
          "pm10Grade": "1",
          "o3Value": "0.047"
        },
        {
          "so2Grade": "1",
          "coFlag": null,
          "khaiValue": "90",
          "so2Value": "0.002",
          "coValue": "0.5",
          "pm25Flag": null,
          "pm10Flag": null,
          "o3Grade": "2",
          "pm10Value": "36",
          "khaiGrade": "2",
          "pm25Value": "22",
          "sidoName": "서울",
          "no2Flag": null,
          "no2Grade": "1",
          "o3Flag": null,
          "pm25Grade": "2",
          "so2Flag": null,
          "dataTime": "2023-07-05 18:00",
          "coGrade": "1",
          "no2Value": "0.010",
          "stationName": "송파구",
          "pm10Grade": "2",
          "o3Value": "0.078"
        },
        {
          "so2Grade": "1",
          "coFlag": null,
          "khaiValue": "78",
          "so2Value": "0.002",
          "coValue": "0.4",
          "pm25Flag": null,
          "pm10Flag": null,
          "o3Grade": "2",
          "pm10Value": "33",
          "khaiGrade": "2",
          "pm25Value": "22",
          "sidoName": "서울",
          "no2Flag": null,
          "no2Grade": "1",
          "o3Flag": null,
          "pm25Grade": "1",
          "so2Flag": null,
          "dataTime": "2023-07-05 18:00",
          "coGrade": "1",
          "no2Value": "0.009",
          "stationName": "강동구",
          "pm10Grade": "1",
          "o3Value": "0.063"
        },
        {
          "so2Grade": "1",
          "coFlag": null,
          "khaiValue": "80",
          "so2Value": "0.002",
          "coValue": "0.5",
          "pm25Flag": null,
          "pm10Flag": null,
          "o3Grade": "2",
          "pm10Value": "32",
          "khaiGrade": "2",
          "pm25Value": "18",
          "sidoName": "서울",
          "no2Flag": null,
          "no2Grade": "1",
          "o3Flag": null,
          "pm25Grade": "1",
          "so2Flag": null,
          "dataTime": "2023-07-05 18:00",
          "coGrade": "1",
          "no2Value": "0.018",
          "stationName": "천호대로",
          "pm10Grade": "2",
          "o3Value": "0.066"
        },
        {
          "so2Grade": "1",
          "coFlag": null,
          "khaiValue": "82",
          "so2Value": "0.003",
          "coValue": "0.6",
          "pm25Flag": null,
          "pm10Flag": null,
          "o3Grade": "2",
          "pm10Value": "44",
          "khaiGrade": "2",
          "pm25Value": "23",
          "sidoName": "서울",
          "no2Flag": null,
          "no2Grade": "1",
          "o3Flag": null,
          "pm25Grade": "2",
          "so2Flag": null,
          "dataTime": "2023-07-05 18:00",
          "coGrade": "1",
          "no2Value": "0.012",
          "stationName": "금천구",
          "pm10Grade": "2",
          "o3Value": "0.068"
        },
        {
          "so2Grade": "1",
          "coFlag": null,
          "khaiValue": "77",
          "so2Value": "0.003",
          "coValue": "0.5",
          "pm25Flag": null,
          "pm10Flag": null,
          "o3Grade": "2",
          "pm10Value": "38",
          "khaiGrade": "2",
          "pm25Value": "24",
          "sidoName": "서울",
          "no2Flag": null,
          "no2Grade": "1",
          "o3Flag": null,
          "pm25Grade": "2",
          "so2Flag": null,
          "dataTime": "2023-07-05 18:00",
          "coGrade": "1",
          "no2Value": "0.019",
          "stationName": "시흥대로",
          "pm10Grade": "2",
          "o3Value": "0.063"
        },
        {
          "so2Grade": "1",
          "coFlag": null,
          "khaiValue": "76",
          "so2Value": "0.002",
          "coValue": "0.4",
          "pm25Flag": null,
          "pm10Flag": null,
          "o3Grade": "2",
          "pm10Value": "42",
          "khaiGrade": "2",
          "pm25Value": "28",
          "sidoName": "서울",
          "no2Flag": null,
          "no2Grade": "1",
          "o3Flag": null,
          "pm25Grade": "2",
          "so2Flag": null,
          "dataTime": "2023-07-05 18:00",
          "coGrade": "1",
          "no2Value": "0.009",
          "stationName": "강북구",
          "pm10Grade": "1",
          "o3Value": "0.062"
        },
        {
          "so2Grade": "1",
          "coFlag": null,
          "khaiValue": "-",
          "so2Value": "0.003",
          "coValue": "0.5",
          "pm25Flag": null,
          "pm10Flag": null,
          "o3Grade": "2",
          "pm10Value": "50",
          "khaiGrade": null,
          "pm25Value": "24",
          "sidoName": "서울",
          "no2Flag": null,
          "no2Grade": "1",
          "o3Flag": null,
          "pm25Grade": "2",
          "so2Flag": null,
          "dataTime": "2023-07-05 18:00",
          "coGrade": "1",
          "no2Value": "0.010",
          "stationName": "양천구",
          "pm10Grade": null,
          "o3Value": "0.075"
        },
        {
          "so2Grade": "1",
          "coFlag": null,
          "khaiValue": "85",
          "so2Value": "0.003",
          "coValue": "0.5",
          "pm25Flag": null,
          "pm10Flag": null,
          "o3Grade": "2",
          "pm10Value": "35",
          "khaiGrade": "2",
          "pm25Value": "25",
          "sidoName": "서울",
          "no2Flag": null,
          "no2Grade": "1",
          "o3Flag": null,
          "pm25Grade": "2",
          "so2Flag": null,
          "dataTime": "2023-07-05 18:00",
          "coGrade": "1",
          "no2Value": "0.011",
          "stationName": "노원구",
          "pm10Grade": "1",
          "o3Value": "0.072"
        },
        {
          "so2Grade": "1",
          "coFlag": null,
          "khaiValue": "-",
          "so2Value": "0.003",
          "coValue": "0.5",
          "pm25Flag": null,
          "pm10Flag": null,
          "o3Grade": "2",
          "pm10Value": "33",
          "khaiGrade": null,
          "pm25Value": "21",
          "sidoName": "서울",
          "no2Flag": null,
          "no2Grade": null,
          "o3Flag": null,
          "pm25Grade": "1",
          "so2Flag": null,
          "dataTime": "2023-07-05 18:00",
          "coGrade": "1",
          "no2Value": "0.030",
          "stationName": "화랑로",
          "pm10Grade": "2",
          "o3Value": "0.056"
        }
      ],
      "pageNo": 1,
      "numOfRows": 100
    },
    "header": {
      "resultMsg": "NORMAL_CODE",
      "resultCode": "00"
    }
  }
}